apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: fluent-bit
    targetRevision: 3.1.5
    helm:
      values: |
        daemonset:
          enabled: true
          podTolerations:
            - key: "kubernetes.azure.com/scalesetpriority"
              operator: Equal
              value: spot
              effect: NoSchedule
            - operator: Exists

        rbac:
          create: true

        serviceAccount:
          create: true

        input:
          tail:
            enabled: true
            path: /var/log/containers/*.log
            parser: docker
            multiline: off
            tag: kube.*

        filters:
          kubernetes:
            enabled: true
            match: kube.*

        output:
          es:
            enabled: true
            host: elasticsearch.elasticsearch.svc.cluster.local
            port: 9200
            tls: false
            logstashPrefix: kubernetes
            replaceDots: true
            type: _doc
            match: kube.*

        extraVolumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true

        extraVolumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers

