eck-elasticsearch:
  enabled: true
  elasticsearch:
    version: 8.13.4
    nodeSets:
      - name: master-nodes
        count: 3
        config:
          node.roles: ["master"]
      - name: data-nodes
        count: 3
        config:
          node.roles: ["data"]
      - name: ingest-nodes
        count: 3
        config:
          node.roles: ["ingest"]


eck-agent:
  enabled: false

eck-fleet-server:
  enabled: false

eck-logstash:
  enabled: false

eck-apm-server:
  enabled: false

