eck-elasticsearch:
  enabled: true
  elasticsearch:
    version: 8.13.4
    nodeSets:
      - name: master-nodes
        count: 3
        config:
          node.roles: ["master"]
      - name: data-nodes
        count: 3
        config:
          node.roles: ["data"]
      - name: ingest-nodes
        count: 3
        config:
          node.roles: ["ingest"]

eck-kibana:
  enabled: true
  kibana:
    metadata:
      name: kibana
    spec:
      version: 8.13.4
      count: 1
      config:
        server.publicBaseUrl: https://kibana.mertyakan.com
      elasticsearchRef:
        name: elasticsearch
      http:
        tls:
          selfSignedCertificate:
            disabled: true
      ingress:
        enabled: true
        className: nginx
        hosts:
          - host: kibana.mertyakan.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
              - kibana.mertyakan.com
            secretName: kibana-mertyakan-com-tls

eck-agent:
  enabled: false

eck-fleet-server:
  enabled: false

eck-logstash:
  enabled: false

eck-apm-server:
  enabled: false

