replicas: 3

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.authc.api_key.enabled: true
    xpack.monitoring.collection.enabled: true

secret:
  password: "supersecretpassword"


resources:
  requests:
    cpu: "10m"
    memory: "1Gi"
  limits:
    memory: "2Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi

service:
  type: ClusterIP

