elasticsearch:
  hosts:
    - elasticsearch-master.elasticsearch-bitnami.svc.cluster.local
  port: 9200

ingress:
  enabled: true
  hostname: kibana.mertyakan.com
  tls: true
  selfSigned: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

extraEnvVars:
  - name: SERVER_PUBLICBASEURL
    value: "https://kibana.mertyakan.com"

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m

