apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 8.5.1
    helm:
      releaseName: kibana
      values: |
        fullnameOverride: kibana
        elasticsearchURL: "https://elasticsearch-master:9200"
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: kibana.mertyakan.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - kibana.mertyakan.com
              secretName: kibana-tls
        extraEnvs:
          - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: kibana-token
                key: token

  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

