apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: es-data
  namespace: argocd
spec:
  destination:
    namespace: elastic-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      values: |
        replicas: 3
        nodeGroup: "data"
        roles:
          - data
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "4Gi"
        volumeClaimTemplate:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    syncOptions:
      - CreateNamespace=true

