apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana-bitnami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kibana
    targetRevision: 10.3.4  # Bitnami Kibana chart versiyonu (örnek)
    helm:
      valueFiles:
        - apps/values/kibana-bitnami-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch-bitnami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

