apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/mertyakan/gitops'
    path: apps/efk/values/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
