apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-bitnami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: elasticsearch
    targetRevision: 21.3.3  # veya en güncel sürüm
    helm:
      valueFiles:
        - apps/values/elasticsearch-bitnami-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch-bitnami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

